<a id="top"></a>
<div id="scrn-read" title="links to aid navigation for screen readers">
    [<a href="#content" accesskey="s">skip to main content</a>]
</div>

<div id="header">
    <img id="first" src="<?php echo $this->baseUrl(); ?>/img/rollercoaster.jpg" title="" alt="" />
    <img src="<?php echo $this->baseUrl(); ?>/img/family2.jpg" title="" alt="" />
    <img src="<?php echo $this->baseUrl(); ?>/img/castle.jpg" title="" alt="" />
    <img src="<?php echo $this->baseUrl(); ?>/img/family3.jpg" title="" alt="" />
</div>
