<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headMeta(). "\n";?>
    <?php echo $this->headLink()->appendStylesheet('/css/site.css'); ?>
</head>

<body>
    <?php echo $this->partial("_header.phtml"); ?>
    <div id="container">
        <div id="content">
        <?php echo $this->layout()->content; ?>
        </div>
        <div id="right">
        </div>
    </div>
    <?php echo $this->partial("_footer.phtml", array("date" => date('d.m.Y'))); ?>
</body>
</html>
