<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">

<head>
	<title><?php
		// это комментарий
		echo $this->escape($this->title);
	?></title>
	<meta http-equiv="Content-type" content="text/html;charset=windows-1251" />
</head>

<body>
	<h3><?php echo $this->escape($this->title); ?></h3>	
	<h3><?php echo "<h3>commit</h3>"; ?></h3>	
	<div><?php 
                echo count($this->places);
                // Zend_Debug::dump($this->places);
              ?></div>	
</body>

</html>

